//../../rtl/macro/macro_define.v
../../rtl/common/dff.v
../../rtl/common/SDP_RAM.v
../../rtl/core/ifu.v
../../rtl/core/idu.v
../../rtl/core/regfile.v
../../rtl/core/exu.v
../../rtl/core/exu_alu.v
../../rtl/core/exu_alu_dec.v
../../rtl/core/exu_alu_calc.v
../../rtl/core/exu_alu_bjp.v
../../rtl/core/exu_alu_agu.v
../../rtl/core/macc.v
../../rtl/core/wb.v
../../rtl/core/ctrl.v
../../rtl/mem/imem.v
../../rtl/mem/data_mem.v
../../rtl/core/riscvboy_core_top.v
../../rtl/top/riscvboy_top.v
./tb_top.sv
